# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/service_spec/super_resolution.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/service_spec/super_resolution.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n+service/service_spec/super_resolution.proto\"E\n\x16SuperResolutionRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\r\n\x05scale\x18\x03 \x01(\x05\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2O\n\x0fSuperResolution\x12<\n\x19increase_image_resolution\x12\x17.SuperResolutionRequest\x1a\x06.Imageb\x06proto3')
)




_SUPERRESOLUTIONREQUEST = _descriptor.Descriptor(
  name='SuperResolutionRequest',
  full_name='SuperResolutionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='SuperResolutionRequest.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='SuperResolutionRequest.model', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale', full_name='SuperResolutionRequest.scale', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=116,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Image.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['SuperResolutionRequest'] = _SUPERRESOLUTIONREQUEST
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SuperResolutionRequest = _reflection.GeneratedProtocolMessageType('SuperResolutionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUPERRESOLUTIONREQUEST,
  __module__ = 'service.service_spec.super_resolution_pb2'
  # @@protoc_insertion_point(class_scope:SuperResolutionRequest)
  ))
_sym_db.RegisterMessage(SuperResolutionRequest)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'service.service_spec.super_resolution_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)



_SUPERRESOLUTION = _descriptor.ServiceDescriptor(
  name='SuperResolution',
  full_name='SuperResolution',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=141,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='increase_image_resolution',
    full_name='SuperResolution.increase_image_resolution',
    index=0,
    containing_service=None,
    input_type=_SUPERRESOLUTIONREQUEST,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUPERRESOLUTION)

DESCRIPTOR.services_by_name['SuperResolution'] = _SUPERRESOLUTION

# @@protoc_insertion_point(module_scope)
